name: "Deploy Arcane Arcade Fallout TTRPG Character Sheet"

on:
  push:
    tags:
      - "fallout-character-sheet/v*"

env:
  PROJECT_PATH: WPF_Fallout_Character_Manager/WPF_Fallout_Character_Manager.csproj
  RUNTIME: win-x64
  CONFIGURATION: Release

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }} --runtime ${{ env.RUNTIME }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c ${{ env.CONFIGURATION }} --runtime ${{ env.RUNTIME }} --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} \
          -c ${{ env.CONFIGURATION }} \
          -r ${{ env.RUNTIME }} \
          --self-contained true \
          -p:PublishSingleFile=true \
          --no-build

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload EXE
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: |
            WPF_Fallout_Character_Manager/bin/Release/net8.0-windows/win-x64/publish/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}